package com.sutulovai.jobops.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    NOT_FOUND,
    CONFLICT,
    UNAUTHORIZED,
    FORBIDDEN,
    INTERNAL_ERROR,
    INVALID_CREDENTIALS,
    EMAIL_TAKEN,
    CV_NOT_FOUND,
    COMPANY_NOT_FOUND,
    VACANCY_NOT_FOUND,
    APPLICATION_NOT_FOUND,
    INVALID_STAGE_TRANSITION,
    FILE_STORAGE_ERROR,
    AI_SERVICE_ERROR,
}
