create table weekly_reviews (
    id                           uuid        not null default gen_random_uuid() primary key,
    user_id                      uuid        not null references users (id) on delete cascade,
    week_number                  int         not null,
    week_start_date              date        not null,
    jobs_analyzed                int         not null default 0,
    apply_count                  int         not null default 0,
    maybe_count                  int         not null default 0,
    skip_count                   int         not null default 0,
    direct_applications          int         not null default 0,
    recruiter_messages           int         not null default 0,
    manager_messages             int         not null default 0,
    referral_requests            int         not null default 0,
    follow_ups_sent              int         not null default 0,
    total_responses              int         not null default 0,
    direct_apply_response_rate   numeric(5,2),
    warm_outreach_response_rate  numeric(5,2),
    recruiter_screen_rate        numeric(5,2),
    tech_interview_rate          numeric(5,2),
    stale_count                  int         not null default 0,
    ghosted_count                int         not null default 0,
    salary_blocker_count         int         not null default 0,
    language_blocker_count       int         not null default 0,
    relocation_blocker_count     int         not null default 0,
    ai_summary                   text,
    ai_what_worked               text,
    ai_what_didnt_work           text,
    ai_recommended_changes       text[]      not null default '{}',
    ai_city_recommendations      text[]      not null default '{}',
    created_at                   timestamptz not null default now(),
    unique (user_id, week_number)
);
